# Generated by Django 2.2.3 on 2020-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_auth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'normal'), (2, 'facebook'), (3, 'gmail')], null=True),
        ),
    ]
