# Generated by Django 2.2.3 on 2020-05-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='characters',
            options={'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterField(
            model_name='characters',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Anime'),
        ),
        migrations.CreateModel(
            name='Weebs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('characters', models.ManyToManyField(to='characters.Characters')),
            ],
        ),
    ]
