# Generated by Django 2.2.3 on 2020-05-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(editable=False, null=True, upload_to='photos/characters/None/%Y-%m-%d/thumbnails/%Y-%m-%d/')),
                ('image', models.ImageField(null=True, upload_to='photos/characters/None/%Y-%m-%d/')),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Characters')),
            ],
        ),
    ]
