# Generated by Django 2.2.3 on 2020-05-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20200521_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weebs',
            new_name='Cosplays',
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name_plural': 'Anime'},
        ),
        migrations.AlterModelOptions(
            name='cosplays',
            options={'verbose_name_plural': 'Cosplays'},
        ),
    ]
