# Generated by Django 2.2.3 on 2020-05-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20200528_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterimages',
            name='characters',
        ),
        migrations.AddField(
            model_name='characterimages',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Characters'),
        ),
    ]
