# Generated by Django 2.2.3 on 2020-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20200528_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterimages',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/characters/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='characterimages',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='photos/characters/%Y-%m-%d/thumbnails/%Y-%m-%d/'),
        ),
    ]
